# Default values for ode-tim-worker-service. 
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: ode-tim-worker-service
replicaCount: 1
image:
  repository: cosysdev.azurecr.io/ode-tim-worker-service
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80

probes:
  enabled: false

ingress:
  enabled: false
  path: /configuration
  pathType: Prefix
  host: api.mound-rd.cosysdev.com
  issuer: letsencrypt-production

kafka:
  userName: internal-service
  groupid: 'tim-worker'
  bootstrapServer: message-moundrd-kafka-bootstrap.moundrd.svc.cluster.local:9092

secrets:
  imagePullSecret: cosysdevcr
  connectionStrings:
    Mongo:
      resource: mongo-cs
      key: Mongo
    Redis:
      resource: redis-cs
      key: Redis
  kafkaPassword:
    resource: internal-service
    key: password

connectionStrings:
  identity: https://ident.cosysdev.com

mongoDatabase: mound-road

resources:
  requests:
    cpu: "10m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

nodeSelector: {}
tolerations: []
affinity: {}